class Application: pass
class Range: pass
class MenuBar: pass
class _Worksheet: pass
class Window: pass
class Workbook: pass
class AddIns: pass
class AddIns2: pass
class AutoCorrect: pass
class AutoRecover: pass
class Sheets: pass
class DefaultPivotTableLayoutOptions: pass
class DefaultWebOptions: pass
class Dialogs: pass
class ErrorCheckingOptions: pass
class FileExportConverters: pass
class CellFormat: pass
class MenuBars: pass
class Modules: pass
class MultiThreadedCalculation: pass
class Names: pass
class ODBCErrors: pass
class OLEDBErrors: pass
class ProtectedViewWindows: pass
class QuickAnalysis: pass
class RTD: pass
class RecentFiles: pass
class SmartTagRecognizers: pass
class Speech: pass
class SpellingOptions: pass
class Toolbars: pass
class UsedObjects: pass
class Watches: pass
class Windows: pass
class Workbooks: pass
class WorksheetFunction: pass
class Areas: pass
class Borders: pass
class Characters: pass
class DisplayFormat: pass
class Errors: pass
class Font: pass
class FormatConditions: pass
class Hyperlinks: pass
class Interior: pass
class Phonetic: pass
class Phonetics: pass
class SmartTags: pass
class SoundNote: pass
class SparklineGroups: pass
class Style: pass
class Validation: pass
class Worksheet: pass
class XPath: pass
class Menus: pass
class _Application: pass
class Comments: pass
class CommentsThreaded: pass
class CustomProperties: pass
class HPageBreaks: pass
class ListObjects: pass
class NamedSheetViewCollection: pass
class Outline: pass
class PageSetup: pass
class _Workbook: pass
class Protection: pass
class QueryTables: pass
class Shapes: pass
class Sort: pass
class Tab: pass
class VPageBreaks: pass
class Pane: pass
class WorksheetView: pass
class Panes: pass
class SheetViews: pass
class Graphic: pass
class Page: pass
class Pages: pass
class Connections: pass
class CustomViews: pass
class TableStyle: pass
class IconSets: pass
class Model: pass
class PivotTables: pass
class PublishObjects: pass
class Queries: pass
class Research: pass
class RoutingSlip: pass
class SlicerCaches: pass
class Styles: pass
class TableStyles: pass
class WebOptions: pass
class XmlMaps: pass
class XmlNamespaces: pass
class AllowEditRanges: pass
class SortFields: pass
class HeaderFooter: pass
class TableStyleElements: pass
class WorkbookConnection: pass
class ModelFormatBoolean: pass
class ModelFormatCurrency: pass
class ModelFormatDate: pass
class ModelFormatDecimalNumber: pass
class ModelFormatGeneral: pass
class ModelFormatPercentageNumber: pass
class ModelFormatScientificNumber: pass
class ModelFormatWholeNumber: pass
class ModelMeasures: pass
class ModelRelationships: pass
class ModelTables: pass
class ModelConnection: pass
class Ranges: pass
class CalculatedMembers: pass
